export const browserCoreExamples = [
  "orchid browser status",
  "orchid browser start",
  "orchid browser stop",
  "orchid browser tabs",
  "orchid browser open https://example.com",
  "orchid browser focus abcd1234",
  "orchid browser close abcd1234",
  "orchid browser screenshot",
  "orchid browser screenshot --full-page",
  "orchid browser screenshot --ref 12",
  "orchid browser snapshot",
  "orchid browser snapshot --format aria --limit 200",
  "orchid browser snapshot --efficient",
  "orchid browser snapshot --labels",
];

export const browserActionExamples = [
  "orchid browser navigate https://example.com",
  "orchid browser resize 1280 720",
  "orchid browser click 12 --double",
  'orchid browser type 23 "hello" --submit',
  "orchid browser press Enter",
  "orchid browser hover 44",
  "orchid browser drag 10 11",
  "orchid browser select 9 OptionA OptionB",
  "orchid browser upload /tmp/orchid/uploads/file.pdf",
  'orchid browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "orchid browser dialog --accept",
  'orchid browser wait --text "Done"',
  "orchid browser evaluate --fn '(el) => el.textContent' --ref 7",
  "orchid browser console --level error",
  "orchid browser pdf",
];
