name: Orchid
options:
  bundleIdPrefix: ai.orchid
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "6.0"

packages:
  OrchidKit:
    path: ../shared/OrchidKit
  Swabble:
    path: ../../Swabble

schemes:
  Orchid:
    shared: true
    build:
      targets:
        Orchid: all
    test:
      targets:
        - OrchidTests

targets:
  Orchid:
    type: application
    platform: iOS
    configFiles:
      Debug: Signing.xcconfig
      Release: Signing.xcconfig
    sources:
      - path: Sources
    dependencies:
      - target: OrchidShareExtension
        embed: true
      - target: OrchidWatchApp
      - package: OrchidKit
      - package: OrchidKit
        product: OrchidChatUI
      - package: OrchidKit
        product: OrchidProtocol
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    preBuildScripts:
      - name: SwiftFormat (lint)
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftformat >/dev/null 2>&1; then
            echo "error: swiftformat not found (brew install swiftformat)" >&2
            exit 1
          fi
          swiftformat --lint --config "$SRCROOT/../../.swiftformat" \
            --filelist "$SRCROOT/SwiftSources.input.xcfilelist"
      - name: SwiftLint
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftlint >/dev/null 2>&1; then
            echo "error: swiftlint not found (brew install swiftlint)" >&2
            exit 1
          fi
          swiftlint lint --config "$SRCROOT/.swiftlint.yml" --use-script-input-file-lists
    settings:
      base:
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_ENTITLEMENTS: Sources/Orchid.entitlements
        CODE_SIGN_STYLE: "$(ORCHID_CODE_SIGN_STYLE)"
        DEVELOPMENT_TEAM: "$(ORCHID_DEVELOPMENT_TEAM)"
        PRODUCT_BUNDLE_IDENTIFIER: "$(ORCHID_APP_BUNDLE_ID)"
        PROVISIONING_PROFILE_SPECIFIER: "$(ORCHID_APP_PROFILE)"
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        ENABLE_APPINTENTS_METADATA: NO
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: Orchid
        CFBundleIconName: AppIcon
        CFBundleURLTypes:
          - CFBundleURLName: ai.orchid.ios
            CFBundleURLSchemes:
              - orchid
        CFBundleShortVersionString: "2026.2.21"
        CFBundleVersion: "20260220"
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIBackgroundModes:
          - audio
          - remote-notification
        BGTaskSchedulerPermittedIdentifiers:
          - ai.orchid.ios.bgrefresh
        NSLocalNetworkUsageDescription: Orchid discovers and connects to your Orchid gateway on the local network.
        NSAppTransportSecurity:
          NSAllowsArbitraryLoadsInWebContent: true
        NSBonjourServices:
          - _orchid-gw._tcp
        NSCameraUsageDescription: Orchid can capture photos or short video clips when requested via the gateway.
        NSLocationWhenInUseUsageDescription: Orchid uses your location when you allow location sharing.
        NSLocationAlwaysAndWhenInUseUsageDescription: Orchid can share your location in the background when you enable Always.
        NSMicrophoneUsageDescription: Orchid needs microphone access for voice wake.
        NSSpeechRecognitionUsageDescription: Orchid uses on-device speech recognition for voice wake.
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  OrchidShareExtension:
    type: app-extension
    platform: iOS
    configFiles:
      Debug: Signing.xcconfig
      Release: Signing.xcconfig
    sources:
      - path: ShareExtension
    dependencies:
      - package: OrchidKit
    settings:
      base:
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: "$(ORCHID_CODE_SIGN_STYLE)"
        DEVELOPMENT_TEAM: "$(ORCHID_DEVELOPMENT_TEAM)"
        PRODUCT_BUNDLE_IDENTIFIER: "$(ORCHID_SHARE_BUNDLE_ID)"
        PROVISIONING_PROFILE_SPECIFIER: "$(ORCHID_SHARE_PROFILE)"
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
    info:
      path: ShareExtension/Info.plist
      properties:
        CFBundleDisplayName: Orchid Share
        CFBundleShortVersionString: "2026.2.21"
        CFBundleVersion: "20260220"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).ShareViewController"
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsText: true
              NSExtensionActivationSupportsWebURLWithMaxCount: 1
              NSExtensionActivationSupportsImageWithMaxCount: 10
              NSExtensionActivationSupportsMovieWithMaxCount: 1

  OrchidWatchApp:
    type: application.watchapp2
    platform: watchOS
    deploymentTarget: "11.0"
    sources:
      - path: WatchApp
    dependencies:
      - target: OrchidWatchExtension
    configFiles:
      Debug: Config/Signing.xcconfig
      Release: Config/Signing.xcconfig
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "$(ORCHID_WATCH_APP_BUNDLE_ID)"
    info:
      path: WatchApp/Info.plist
      properties:
        CFBundleDisplayName: Orchid
        CFBundleShortVersionString: "2026.2.21"
        CFBundleVersion: "20260220"
        WKCompanionAppBundleIdentifier: "$(ORCHID_APP_BUNDLE_ID)"
        WKWatchKitApp: true

  OrchidWatchExtension:
    type: watchkit2-extension
    platform: watchOS
    deploymentTarget: "11.0"
    sources:
      - path: WatchExtension/Sources
    dependencies:
      - sdk: WatchConnectivity.framework
      - sdk: UserNotifications.framework
    configFiles:
      Debug: Config/Signing.xcconfig
      Release: Config/Signing.xcconfig
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "$(ORCHID_WATCH_EXTENSION_BUNDLE_ID)"
    info:
      path: WatchExtension/Info.plist
      properties:
        CFBundleDisplayName: Orchid
        CFBundleShortVersionString: "2026.2.21"
        CFBundleVersion: "20260220"
        NSExtension:
          NSExtensionAttributes:
            WKAppBundleIdentifier: "$(ORCHID_WATCH_APP_BUNDLE_ID)"
          NSExtensionPointIdentifier: com.apple.watchkit

  OrchidTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: Orchid
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.orchid.ios.tests
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Orchid.app/Orchid"
        BUNDLE_LOADER: "$(TEST_HOST)"
    info:
      path: Tests/Info.plist
      properties:
        CFBundleDisplayName: OrchidTests
        CFBundleShortVersionString: "2026.2.21"
        CFBundleVersion: "20260220"
