#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${ORCHID_INSTALL_E2E_IMAGE:-${ORCHID_INSTALL_E2E_IMAGE:-orchid-install-e2e:local}}"
INSTALL_URL="${ORCHID_INSTALL_URL:-${ORCHID_INSTALL_URL:-https://orchid.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
ORCHID_E2E_MODELS="${ORCHID_E2E_MODELS:-${ORCHID_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e ORCHID_INSTALL_URL="$INSTALL_URL" \
  -e ORCHID_INSTALL_TAG="${ORCHID_INSTALL_TAG:-${ORCHID_INSTALL_TAG:-latest}}" \
  -e ORCHID_E2E_MODELS="$ORCHID_E2E_MODELS" \
  -e ORCHID_INSTALL_E2E_PREVIOUS="${ORCHID_INSTALL_E2E_PREVIOUS:-${ORCHID_INSTALL_E2E_PREVIOUS:-}}" \
  -e ORCHID_INSTALL_E2E_SKIP_PREVIOUS="${ORCHID_INSTALL_E2E_SKIP_PREVIOUS:-${ORCHID_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
